### ISSUE TITLE
[Request] List of changes to make this official

### ISSUE THREAD

**Issue by mmmarinho** [dqrobotics/cpp-interface-coppeliasim-zmq#1]
Hi, @juanjqo,

This starts from your self-identified unofficial package. Here is a dynamic list of steps to make this official

@juanjqo 
- [X] Remove (from this repo) the Matlab version, because this will eventually be on its repo (Done in #2)
- [X] Be sure that this is an implementation from the class in https://github.com/dqrobotics/cpp-interface-coppeliasim/issues/1 (Done in #2)
- [X] Please be sure it works in Ubuntu 22.04 and forward. Ubuntu 20.04 is not needed because the EOL is April 2025. https://ubuntu.com/about/release-cycle (Done in #2)
- [X] Please think of an interface that makes it clear what methods are from the original abstract class (the ones we'll commit to supporting) and the many additional ones that you have enabled by zmq.  ~For instance, you can create those in a different namespace called experimental.~ Those methods are nice and very welcome but it's a lot to commit to support officially. (Done in #2)
- [ ] Add the abstract version of CoppeliaSimRobot to https://github.com/dqrobotics/cpp-interface-coppeliasim
- [ ] Add the CoppeliaSimRobotZMQ to this repository
- [ ] Add the CoppeliaSimRobotZMQExtended (if applicable) to this repository
- [ ] Add the constructor with an atomic_bool to break any loops. See below. This is important if there are any loops in the interface, so the external application must be able to break them. If no loops exist (there's no blocking method) then this might not be needed.
- [ ] Remove the submodule `cppzmq`, it does not seem to be used for this version.
    - https://github.com/zeromq/cppzmq/tree/6541dd1ce9c12bb252e4f7277ad35d3d80270dd1

https://github.com/dqrobotics/cpp-interface-vrep/blob/b7517390d48ff6a5ae6feb56d5c1fdadd20ceeae/include/dqrobotics/interfaces/vrep/DQ_VrepInterface.h#L67
 

@mmmarinho 
- [x] #3
- [x] Update https://github.com/SmartArmStack/smart_arm_stack_ROS2 to support this.
- [x] Add to devel PPA
     - https://code.launchpad.net/~dqrobotics-dev/+recipe/dqrobotics-interface-coppeliasim-dev
     - https://code.launchpad.net/~dqrobotics-dev/dqrobotics/+git/dqrobotics-cpp-interface-coppeliasim-zmq

**Comment by juanjqo** [comment]
@mmmarinho thanks for the detailed steps. I'm going to work on it!

**Comment by juanjqo** [comment]
Current development status:

- [x] Create an abstract DQ_CoppeliaSimInterface class based on https://github.com/dqrobotics/matlab/pull/112
- [x] Remove the Matlab version
- [x] Added the required submodules. Fetch strategies won't work in Debian recipes.
- [x] Test the interface on Ubuntu 22. 
- [x] Updated the README accordingly.
- [x] Experimental methods are required to be in a different namespace.
- [x] Document all methods that are override from `DQ_CoppeliaSimInterface` and the new ones. Experimental methods or private ones won't be well documented at this stage. 
- [x] Perform exhaustive tests using the current examples and unit tests based on [gtest](https://github.com/google/googletest/)

**Comment by mmmarinho** [comment]
Hi @juanjqo,

I can see that the experimental methods are isolated now in the nested class. @bvadorno's suggestion is to do that in a subclass to further isolate things.

For instance

- DQ_CoppeliaSimInterfaceZMQ: Supported methods
- DQ_CoppeliaSimInterfaceZMQExperimental: Experimental methods

It will probably be easier for you to manage the code as well because you just need to set the supported API as `protected` and has less stuff to worry about in the Experimental subclass.

**Comment by juanjqo** [comment]
Hi @mmmarinho, 

I am going to implement the @bvadorno 's suggestion.

Cheers,

Juancho

**Comment by mmmarinho** [comment]
@juanjqo 

Also, for naming, maybe consider

- **DQ_CoppeliaSimInterface** (Abstract)
- **DQ_CoppeliaSimInterface**_ZMQ_
- **DQ_CoppeliaSimInterface**_ZMQExperimental_

and

- **DQ_CoppeliaSimRobot** (Abstract)
- **DQ_CoppeliaSimRobot**_ZMQ_
- **DQ_CoppeliaSimRobot**_ZMQExperimental_

So that future interfaces, when needed, become

- **DQ_CoppeliaSimInterface**_{something}_

We have been naming either leading or trailing, so it's fine to choose one, but maybe not the best idea to insert the ZMQ between names.

Trailing

- DQ_SerialManipulator
- DQ_SerialManipulatorDH

Leading

- DQ_**KinematicConstrained**Controller
- DQ_**NumericalFilteredPseudoInverse**Controller

**Comment by mmmarinho** [comment]
Hi @juanjqo,

I'm really missing this functionality. Would you have any availability to take a look a this one?
https://github.com/dqrobotics/cpp-interface-vrep/blob/master/include/dqrobotics/interfaces/vrep/DQ_VrepRobot.h

Kind regards,
Murilo

**Comment by juanjqo** [comment]
Hi @mmmarinho, sure, I'm going to add it!
